### ISSUE TITLE
Where we can config jaeger endpoint in the middleware for echo microservices

### ISSUE THREAD

**Issue by crizstian** [carlosedp/go-playground#1]
how does the echo middleware where to send the metrics to jaeger ?

is there a config for that ?
or how the metrics are collected and then sent to prometheus ?

**Comment by crizstian** [comment]
I think I have my answer here https://github.com/jaegertracing/jaeger-client-go#environment-variables

I can make use of the jaeger environment variables to set the jaeger configuration

**Comment by carlosedp** [comment]
Exactly! I'll update the readme with this info.

**Comment by carlosedp** [comment]
Updated on https://github.com/carlosedp/go-playground/commit/c5ad7d6ce0788ee67b519ac684d24f559059bd49.
